ci

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -67,6 +67,10 @@ jobs:
           curl -LO "https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl"
           chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
 
+      - name: Get CI host (docker0) IP
+        run: |
+          HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
+          echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
       - name: Create kind cluster with kind-config-ci
         run: |
           kind create cluster --config kind-config-ci.yaml
@@ -81,7 +85,9 @@ jobs:
 
       - name: Install app with Helm
         run: |
-          helm install my-app ./chart -f ./chart/values-ci.yaml -n default --wait --timeout 2m || echo "Helm failed but continuing..."
+          helm install my-app ./chart -f ./chart/values-ci.yaml -n default --wait --timeout 2m
+          --set registry.url=${{ env.HOST_IP }}:5000
+          --set docker.insecureRegistry=${{ env.HOST_IP }}:5000 || echo "Helm failed but continuing..."
       - name: Debug Pod Status
         run: |
           kubectl get pods -n default
